### ISSUE TITLE
Unable to log into Tailascale on QTS 5

### ISSUE THREAD

**Issue by wingcomm** [tailscale/tailscale-qpkg#82]
When I install Tailscale 1.36.1 and go to login, the login page does not work from the App Center:

<img width="546" alt="Screenshot 2023-02-23 at 2 32 13 AM" src="https://user-images.githubusercontent.com/9159510/220844223-c8cb6f6e-b216-44d9-80cf-b29d0aeee340.png">

BUG-b37da539824d0dbd7765cdf1c0b358b50fe9a381c15d8f707f72eaff0ac48920-20230223072039Z-b002af7f0573e0de

**Comment by wingcomm** [comment]
After trying a reboot, I get the following screen.

<img width="370" alt="Screenshot 2023-02-23 at 3 46 26 AM" src="https://user-images.githubusercontent.com/9159510/220859666-45bd593f-0a17-439a-8d04-50a73e19aeb6.png">
hot.

**Comment by DentonGentry** [comment]
The case that we know is currently broken is https://github.com/tailscale/tailscale/issues/7108, if the WebUI port has been changed. That manifests as a different symptom than EOF error, though. 

From the ssh prompt:
- is `ps auxw | grep tailscale` running?
- I believe logs are staged in /tmp/tailscale while trying to upload, are there any *.log files there?

> BUG-94e4712067ad62896f72687f604afc9d229d67918c925743b74cc6c77a787435-20230223085756Z-db18b1e2fae0ab07

Unfortunately this system has never managed to upload telemetry, there is nothing to go on.

**Comment by wingcomm** [comment]
Yes, its running

`[~] # ps auxw | grep tailscale
  802 admin     71572 S   /share/CACHEDEV1_DATA/.qpkg/Tailscale/tailscaled --port 41641 --statedir=/share/CACHEDEV1_DATA/.qpkg/Tailscale/state --socket=/tmp/tailscale/tailscaled.sock
11841 admin      1000 S   grep tailscale`

There are no logs in /tmp/tailscale:

```
[/tmp/tailscale] # ls -al
total 4
drwxr-xr-x  2 admin administrators   80 2023-02-23 02:37 ./
drwxrwxrwx 28 admin administrators 3240 2023-02-24 01:29 ../
-rw-rw-rw-  1 admin administrators    4 2023-02-23 02:37 tailscaled.pid
srw-rw-rw-  1 admin administrators    0 2023-02-23 02:37 tailscaled.sock=
```

Here is another bug report:
BUG-94e4712067ad62896f72687f604afc9d229d67918c925743b74cc6c77a787435-20230224063044Z-a9c44fa597e636d9

BUG-94e4712067ad62896f72687f604afc9d229d67918c925743b74cc6c77a787435-20230224063044Z-a9c44fa597e636d9

**Comment by DentonGentry** [comment]
I understand that you want a fix. I promise that we will update the issue when progress is made.

**Comment by wingcomm** [comment]
@DentonGentry Has Tailscale stopped releasing updates for QNAP?

**Comment by DentonGentry** [comment]
We are focussing on getting the package into the QNAP App Center. Every time we would do a new release, it would disrupt that process as they updated to the new build. We are aiming to get 1.36 into the App Center.

**Comment by wingcomm** [comment]
@DentonGentry None of the currently available builds work on QNAP anymore. Shouldn't that be addressed first?

**Comment by DentonGentry** [comment]
We test every build on a TS231K. I understand that people who use the CLI to add additional options may have trouble, but that is not the main use for this package.

**Comment by wingcomm** [comment]
@DentonGentry I was referring to this issue and other issues that seem to be similar with login/connection issues on QNAP such as: https://github.com/tailscale/tailscale-qpkg/issues/83

**Comment by talios** [comment]
Ditto for @wingcomm's comment - none of the recent builds have worked for me - no network access at all.  That, and since I run off a different port the new GUI support doesn't work either ( no idea if that's been fixed at all, and not sure of the issue number off hand).

**Comment by wingcomm** [comment]
@DentonGentry Are you testing unbinding and rebinding the QNAP to a Tailnet? Something is getting missed in Tailscale's testing regimen.

I still don't quite understand why this update process disrupts the QNAP App Store process. The QNAP App Center is notoriously slow to release updates. Why not post them to pkgs.tailscale.com in the same way that Synology packages are posted?

**Comment by DentonGentry** [comment]
> Are you testing unbinding and rebinding the QNAP to a Tailnet? Something is getting missed in Tailscale's testing regimen.

We test logging out and logging in, using the `tailscale web` console. We're not routinely testing use of `tailscale up` from a shell after SSH, which is how people have been doing things like advertising routes from QNAP devices.

One is welcome to use SSH, but the options we'll be prepared to support are those in the web console such as advertising as an exit node.

> I still don't quite understand why this update process disrupts the QNAP App Store process. The QNAP App Center is notoriously slow to release updates.

We started the QNAP review process some time ago, and updated it to 1.36 mid-review. For platforms with long lead times to deliver an update we tend to stay one release behind, expecting to find any significant issues or accidental regressions via the platforms where we can address a problem more quickly. So we did not build 1.38 for QNAP, and expected 1.36 to debut in the App Center and we would build a 1.38 once the rest of the platforms had fully exercised it.

At this point I don't expect 1.36 to appear in the App Center. We're relatively close to releasing 1.40 for all platforms, I expect to build a 1.40 for QNAP platforms, post it here and submit it to the test process.

> Why not post them to pkgs.tailscale.com in the same way that Synology packages are posted?

The platforms which appear on pkgs.tailscale.com are handled by an autobuilder. Packages for QNAP are still built manually. We'll add QNAP to the autobuilder when we're ready to officially announce support, after it appears in in App Center and our support materials are prepared for how to answer common support questions.

**Comment by wingcomm** [comment]
@DentonGentry Thank you for your feedback and your team's persistence. My issue appears to be resolved now that 1.40.0 has been published for QNAP. I am able to connect my QNAP to my tailnet again using the Web UI.
